MYZSH=$HOME/src/My.Zsh

THEME=$MYZSH/themes/lxsameer.zsh-theme

# Example aliases
#alias emacsw="emacs -nw"

source $MYZSH/my.zsh
PROJECTS=$HOME/Projects
#eval $(keychain --eval --agents ssh -Q --quiet id_rsa)

#export PATH=/home/lxsameer/.gem/ruby/2.0.0/bin:$PATH
#export GEM_HOME=~/.gem/

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

#Cordova settings
export ANDROID_HOME="/home/yottanami/bin/android/adt-bundle-linux-x86_64-20131030/sdk"
export PATH=${PATH}:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64/

project_path=${PROJECTS:-~/Projects}
yellowen_path=$project_path/yellowen
cdpath=($project_path $cdpath $yellowen_path)

######## Generated by Betty's install script
alias betty=/home/yottanami/betty/main.rb

######## Generated by Betty's install script
alias betty=/home/yottanami/betty/main.rb

######## Generated by Betty's install script
alias betty=/home/yottanami/betty/main.rb
